// Generated by CoffeeScript 1.3.3
var loadWallpapers;

loadWallpapers = function() {
  var i, size, _i, _results;
  _results = [];
  for (i = _i = 9; _i >= 1; i = --_i) {
    _results.push((function() {
      var _j, _len, _ref, _results1;
      _ref = ['a', 'b'];
      _results1 = [];
      for (_j = 0, _len = _ref.length; _j < _len; _j++) {
        size = _ref[_j];
        _results1.push($('#psg').append("<a href='/img/wallpaper/" + (i + size) + ".jpg' target='_blank'><img class='wallpaper' src='/img/wallpaper/thumb/" + (i + size) + ".jpg'></a>"));
      }
      return _results1;
    })());
  }
  return _results;
};

$(function() {
  return loadWallpapers();
});
