application: adegleyoyos
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style
  
- url: /image
  static_dir: image
  
- url: /script
  static_dir: script
  
- url: .*
  script: main.py
