application: adegleyoyos
version: 1
runtime: python27
api_version: 1
threadsafe : no

handlers:
- url: /css
  static_dir: css
  
- url: /img
  static_dir: img
  
- url: /js
  static_dir: js
  
- url: .*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest
